title: Suami Medeiros
logo: "/assets/portfolio.jpg"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/surocham/">LinkedIn</a> |
  <a href="https://suamimedeiros.github.io/">Portfólio</a> |
  <a href="https://github.com/surocham">GitHub</a> |
  <a href="mailto:suamirochati@gmail.com">E-mail</a> |
  <a href="/assets/CV_Analista_Suami_Medeiros_2026.pdf" download>Baixar CV</a> 
  </p>
  
  <p align="center">
   Olá! <br> 
   Aqui, compartilho como aplico soluções em Dados para resolver problemas de negócios.
   
   </p>
   <p align="center">
   <a href="#inicio">Início</a> <br>
   <a href="#projetos">Projetos de Dados</a> <br>
   </p> 
   </p>
   <p align="center">
   <br><br>
   </p>
theme: jekyll-theme-minimal
